### ISSUE TITLE
Add two more plots

### ISSUE THREAD

**Issue by JesseLivezey** [a-krishnan7/minmaxchancap#5]
In addition to plotting the initial Pyhy, can you also plot the resulting Pyhy from the minimization and maximization? You'll need to reshape the result to (n, n) before plotting.

**Comment by a-krishnan7** [comment]
Hi Jesse,

I plotted the Pyhy outputs from the minimization and maximization and
pushed to github at github.com/a-krishnan7/minmaxchancap. I think I have a
pretty good basic understanding of how the optimization works, but I'm not
really sure what the image plotted is telling us. Can we Skype sometime in
the afternoon/evening this week? I'm free on most days next except
Wednesday.

Thanks!
-Amrith
